# Generated by Django 3.2.7 on 2021-10-06 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCapacitacion',
            fields=[
                ('idAreaCap', models.AutoField(primary_key=True, serialize=False, verbose_name='id_area_cap')),
                ('area', models.CharField(max_length=45, verbose_name='area')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('idCapacitacion', models.AutoField(primary_key=True, serialize=False, verbose_name='id_capacitacion')),
                ('curso', models.CharField(max_length=45, verbose_name='curso')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('idAreaCapacitacionFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_area_cap', to='AuthAppEmpleados.areacapacitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('idCargo', models.AutoField(primary_key=True, serialize=False, verbose_name='id_cargo')),
                ('cargo', models.CharField(max_length=45, verbose_name='cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('name', models.CharField(max_length=30, verbose_name='nombre')),
                ('email', models.EmailField(max_length=30, verbose_name='email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='cedula')),
                ('nombres', models.CharField(max_length=50, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='apellidos')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('cargoIdFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_id_fk', to='AuthAppEmpleados.cargos')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False, verbose_name='id_registro')),
                ('cedulaTrabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cedula_trabajador', to='AuthAppEmpleados.trabajadores')),
                ('idCapacitacionFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_capacitacion_fk', to='AuthAppEmpleados.capacitacion')),
            ],
        ),
        migrations.CreateModel(
            name='CargosCapacitacion',
            fields=[
                ('idCarCap', models.AutoField(primary_key=True, serialize=False, verbose_name='id_car_cap')),
                ('idAreaCapFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_area_cap_fk', to='AuthAppEmpleados.areacapacitacion')),
                ('idCargoFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cargo_fk', to='AuthAppEmpleados.cargos')),
            ],
        ),
    ]
